USE [master]
GO
/****** Object:  Database [RESTOBAR_DB]    Script Date: 4/6/2026 23:23:04 ******/
CREATE DATABASE [RESTOBAR_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RESTOBAR_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RESTOBAR_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RESTOBAR_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RESTOBAR_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RESTOBAR_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RESTOBAR_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RESTOBAR_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RESTOBAR_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RESTOBAR_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RESTOBAR_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RESTOBAR_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [RESTOBAR_DB] SET  MULTI_USER 
GO
ALTER DATABASE [RESTOBAR_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RESTOBAR_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RESTOBAR_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RESTOBAR_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RESTOBAR_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RESTOBAR_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RESTOBAR_DB', N'ON'
GO
ALTER DATABASE [RESTOBAR_DB] SET QUERY_STORE = OFF
GO
USE [RESTOBAR_DB]
GO
/****** Object:  Table [dbo].[CATEGORIAS]    Script Date: 4/6/2026 23:23:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIAS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSUMOS]    Script Date: 4/6/2026 23:23:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSUMOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Descripcion] [varchar](200) NULL,
	[Precio] [decimal](10, 2) NOT NULL,
	[Stock] [int] NOT NULL,
	[IdCategoria] [int] NOT NULL,
	[Activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INSUMOS] ADD  DEFAULT ((1)) FOR [Activo]
GO
ALTER TABLE [dbo].[INSUMOS]  WITH CHECK ADD  CONSTRAINT [FK_INSUMOS_CATEGORIAS] FOREIGN KEY([IdCategoria])
REFERENCES [dbo].[CATEGORIAS] ([Id])
GO
ALTER TABLE [dbo].[INSUMOS] CHECK CONSTRAINT [FK_INSUMOS_CATEGORIAS]
GO
USE [master]
GO
ALTER DATABASE [RESTOBAR_DB] SET  READ_WRITE 
GO
